# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emailsSent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'emailsSent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65mailsSent.proto\x12\nemailssent\"@\n\x13UpdateEmailsRequest\x12\r\n\x05\x65mpid\x18\x01 \x01(\t\x12\x1a\n\x12numberOfemailsSent\x18\x02 \x01(\x05\"8\n\x14UpdateEmailsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2`\n\x0bUserService\x12Q\n\x0cUpdateEmails\x12\x1f.emailssent.UpdateEmailsRequest\x1a .emailssent.UpdateEmailsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emailsSent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEEMAILSREQUEST']._serialized_start=32
  _globals['_UPDATEEMAILSREQUEST']._serialized_end=96
  _globals['_UPDATEEMAILSRESPONSE']._serialized_start=98
  _globals['_UPDATEEMAILSRESPONSE']._serialized_end=154
  _globals['_USERSERVICE']._serialized_start=156
  _globals['_USERSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
