# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x05leave\"\xfd\x01\n\x0cLeaveRequest\x12\x13\n\x0b\x63urrentMood\x18\x05 \x01(\t\x12\x13\n\x0bisEscalated\x18\x06 \x01(\x08\x12\x18\n\x10\x62riefMoodSummary\x18\x07 \x01(\t\x12\x17\n\x0f\x63urrentMoodRate\x18\x08 \x01(\t\x12\x10\n\x08userChat\x18\t \x01(\t\x12\x0f\n\x07\x62otChat\x18\n \x01(\t\x12\r\n\x05\x65mpid\x18\x0b \x01(\t\x12\x15\n\rwellnessScore\x18\x0c \x01(\x05\x12\x14\n\x0cmoodAnalysis\x18\r \x01(\t\x12\x19\n\x11recommendedAction\x18\x0e \x01(\t\x12\x16\n\x0e\x63hatAIAnalysis\x18\x0f \x01(\t\"/\n\rLeaveResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05jobId\x18\x02 \x01(\t2O\n\x0cLeaveService\x12?\n\x12SubmitLeaveRequest\x12\x13.leave.LeaveRequest\x1a\x14.leave.LeaveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEAVEREQUEST']._serialized_start=22
  _globals['_LEAVEREQUEST']._serialized_end=275
  _globals['_LEAVERESPONSE']._serialized_start=277
  _globals['_LEAVERESPONSE']._serialized_end=324
  _globals['_LEAVESERVICE']._serialized_start=326
  _globals['_LEAVESERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
